/*
 * spi_nand_flash_tables.c
 * SPI NAND Flash device tables.
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#include "spi_nand_flash.h"
#include "spi_nand_flash_defs.h"
#include <stddef.h> // For size_t

/*****************************[ Notice]******************************/
/* This file contains the full table of supported SPI NAND devices. */
/*****************************[ Notice]******************************/

/* Define the actual table */
const struct SPI_NAND_FLASH_INFO_T spi_nand_flash_tables[] = {
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GQ4UAYIG,
	    ptr_name : "GIGADEVICE GD5F1GQ4UA",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F2GQ4UAYIG,
	    ptr_name : "GIGADEVICE GD5F2GQ4UA",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GQ4UBYIG,
	    ptr_name : "GIGADEVICE GD5F1GQ4UB",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GQ4REYIG,
	    ptr_name : "GIGADEVICE GD5F1GQ4RE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GQ4UCYIG,
	    ptr_name : "GIGADEVICE GD5F1GQ4UC",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_PREPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GQ4UEYIS,
	    ptr_name : "GIGADEVICE GD5F1GQ4UE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GQ5UEYIG,
	    ptr_name : "GIGADEVICE GD5F1GQ5UE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GQ5REYIG,
	    ptr_name : "GIGADEVICE GD5F1GQ5RE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F2GQ5UEYIG,
	    ptr_name : "GIGADEVICE GD5F2GQ5UE",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F2GQ5REYIG,
	    ptr_name : "GIGADEVICE GD5F2GQ5RE",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GM7UEYIG,
	    ptr_name : "GIGADEVICE GD5F1GM7UE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F1GM7REYIG,
	    ptr_name : "GIGADEVICE GD5F1GM7RE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F2GM7UEYIG,
	    ptr_name : "GIGADEVICE GD5F2GM7UE",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F2GM7REYIG,
	    ptr_name : "GIGADEVICE GD5F2GM7RE",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F2GQ4UBYIG,
	    ptr_name : "GIGADEVICE GD5F2GQ4UB",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "GIGADEVICE GD5F2GQ4UE",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F2GQ4UE9IS,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F2GQ4UCYIG,
	    ptr_name : "GIGADEVICE GD5F2GQ4UC",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_PREPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F4GQ4UBYIG,
	    ptr_name : "GIGADEVICE GD5F4GQ4UB",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_GIGADEVICE,
	    dev_id : _SPI_NAND_DEVICE_ID_GD5F4GQ4UCYIG,
	    ptr_name : "GIGADEVICE GD5F4GQ4UC",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_PREPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ESMT,
	    dev_id : _SPI_NAND_DEVICE_ID_F50D1G41LB,
	    ptr_name : "ESMT F50D1G41LB(2M)",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ESMT,
	    dev_id : _SPI_NAND_DEVICE_ID_F50L512M41A,
	    ptr_name : "ESMT F50L512",
	    device_size : _SPI_NAND_CHIP_SIZE_512MBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ESMT,
	    dev_id : _SPI_NAND_DEVICE_ID_F50L1G41A0,
	    ptr_name : "ESMT F50L1G",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ESMT,
	    dev_id : _SPI_NAND_DEVICE_ID_F50L1G41LB,
	    ptr_name : "ESMT F50L1G41LB",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ESMT,
	    dev_id : _SPI_NAND_DEVICE_ID_F50L2G41LB,
	    ptr_name : "ESMT F50L2G41LB",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_DIE_SELECT_1_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_WINBOND,
	    dev_id : _SPI_NAND_DEVICE_ID_1_W25N01KV,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_W25N01KV,
	    ptr_name : "WINBOND W25N01KV",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_WINBOND,
	    dev_id : _SPI_NAND_DEVICE_ID_1_W25N01GV,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_W25N01GV,
	    ptr_name : "WINBOND W25N01GV",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_WINBOND,
	    dev_id : _SPI_NAND_DEVICE_ID_1_W25N01GW,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_W25N01GW,
	    ptr_name : "WINBOND W25N01GW",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_WINBOND,
	    dev_id : _SPI_NAND_DEVICE_ID_1_W25N02KV,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_W25N02KV,
	    ptr_name : "WINBOND W25N02KV",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_WINBOND,
	    dev_id : _SPI_NAND_DEVICE_ID_1_W25N04KV,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_W25N04KV,
	    ptr_name : "WINBOND W25N04KV",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_WINBOND,
	    dev_id : _SPI_NAND_DEVICE_ID_1_W25N04KW,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_W25N04KW,
	    ptr_name : "WINBOND W25N04KW",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_WINBOND,
	    dev_id : _SPI_NAND_DEVICE_ID_1_W25M02GV,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_W25M02GV,
	    ptr_name : "WINBOND W25M02GV",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_DIE_SELECT_1_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_MX35LF1GE4AB,
	    ptr_name : "MXIC MX35LF1GE4AB",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_MX35LF2GE4AB,
	    ptr_name : "MXIC MX35LF2GE4AB",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_MX35LF2G14AC,
	    ptr_name : "MXIC MX35LF2G14AC",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_MX35UF1G14AC,
	    ptr_name : "MXIC MX35UF1G14AC",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_MX35UF2G14AC,
	    ptr_name : "MXIC MX35UF2G14AC",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35LF2GE4AD,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35LF2GE4AD,
	    ptr_name : "MXIC MX35LF2GE4AD",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35LF1G24AD,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35LF1G24AD,
	    ptr_name : "MXIC MX35LF1G24AD",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35LF2G24AD,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35LF2G24AD,
	    ptr_name : "MXIC MX35LF2G24AD",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35LF4G24AD,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35LF4G24AD,
	    ptr_name : "MXIC MX35LF4G24AD",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35LF2G24ADZ4I8,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35LF2G24ADZ4I8,
	    ptr_name : "MXIC MX35LF2G24AD-Z4I8",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35LF4G24ADZ4I8,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35LF4G24ADZ4I8,
	    ptr_name : "MXIC MX35LF4G24AD-Z4I8",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35UF1GE4AD,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35UF1GE4AD,
	    ptr_name : "MXIC MX35UF1GE4AD",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35UF2GE4AD,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35UF2GE4AD,
	    ptr_name : "MXIC MX35UF2GE4AD",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MXIC,
	    dev_id : _SPI_NAND_DEVICE_ID_1_MX35UF4GE4AD,
	    dev_id_2 : _SPI_NAND_DEVICE_ID_2_MX35UF4GE4AD,
	    ptr_name : "MXIC MX35UF4GE4AD",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ZENTEL,
	    dev_id : _SPI_NAND_DEVICE_ID_A5U12A21ASC,
	    ptr_name : "ZENTEL A5U12A21ASC",
	    device_size : _SPI_NAND_CHIP_SIZE_512MBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ZENTEL,
	    dev_id : _SPI_NAND_DEVICE_ID_A5U1GA21BWS,
	    ptr_name : "ZENTEL A5U1GA21BWS",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    /* Etron */
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73C044SNB,
	    ptr_name : "ETRON EM73C044SNB",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73C044SND,
	    ptr_name : "ETRON EM73C044SND",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "ETRON EM73C044SNF",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73C044SNF,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "ETRON EM73C044VCA",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73C044VCA,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "ETRON EM73C044VCD",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73C044VCD,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "ETRON EM73D044VCA",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044VCA,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "ETRON EM73D044VCB",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044VCB,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "ETRON EM73D044VCD",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044VCD,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "ETRON EM73D044VCG",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044VCG,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "ETRON EM73D044VCH",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044VCH,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044SNA,
	    ptr_name : "ETRON EM73D044SNA",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044SNC,
	    ptr_name : "ETRON EM73D044SNC",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044SND,
	    ptr_name : "ETRON EM73D044SND",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73D044SNF,
	    ptr_name : "ETRON EM73D044SNF",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ETRON,
	    dev_id : _SPI_NAND_DEVICE_ID_EM73E044SNA,
	    ptr_name : "ETRON EM73E044SNA",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_TOSHIBA,
	    dev_id : _SPI_NAND_DEVICE_ID_TC58CVG0S3H,
	    ptr_name : "TOSHIBA TC58CVG0S3H",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_TOSHIBA,
	    dev_id : _SPI_NAND_DEVICE_ID_TC58CVG1S3H,
	    ptr_name : "TOSHIBA TC58CVG1S3H",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_TOSHIBA,
	    dev_id : _SPI_NAND_DEVICE_ID_TC58CVG2S0H,
	    ptr_name : "TOSHIBA TC58CVG2S0H",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_TOSHIBA,
	    dev_id : _SPI_NAND_DEVICE_ID_TC58CVG2S0HRAIJ,
	    ptr_name : "KIOXIA TC58CVG2S0HRAIJ",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F1G01AA,
	    ptr_name : "MICRON MT29F1G01AA",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F2G01AA,
	    ptr_name : "MICRON MT29F2G01AA",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F4G01AA,
	    ptr_name : "MICRON MT29F4G01AA",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE | SPI_NAND_FLASH_DIE_SELECT_2_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F1G01AB,
	    ptr_name : "MICRON MT29F1G01AB",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F2G01ABA,
	    ptr_name : "MICRON MT29F2G01ABA",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F2G01ABB,
	    ptr_name : "MICRON MT29F2G01ABB",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F4G01ABA,
	    ptr_name : "MICRON MT29F4G01ABA",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F4G01ABB,
	    ptr_name : "MICRON MT29F4G01ABB",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MICRON,
	    dev_id : _SPI_NAND_DEVICE_ID_MT29F4G01AD,
	    ptr_name : "MICRON MT29F4G01AD",
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_4KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_256BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_256KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_DIE_SELECT_2_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_HEYANG,
	    dev_id : _SPI_NAND_DEVICE_ID_HYF1GQ4UAACAE,
	    ptr_name : "HEYANG HYF1GQ4UAACAE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_HEYANG,
	    dev_id : _SPI_NAND_DEVICE_ID_HYF2GQ4UAACAE,
	    ptr_name : "HEYANG HYF2GQ4UAACAE",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_HEYANG,
	    dev_id : _SPI_NAND_DEVICE_ID_HYF2GQ4UHCCAE,
	    ptr_name : "HEYANG HYF2GQ4UHCCAE",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_HEYANG,
	    dev_id : _SPI_NAND_DEVICE_ID_HYF1GQ4UDACAE,
	    ptr_name : "HEYANG HYF1GQ4UDACAE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_HEYANG,
	    dev_id : _SPI_NAND_DEVICE_ID_HYF2GQ4UDACAE,
	    ptr_name : "HEYANG HYF2GQ4UDACAE",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_HEYANG_2,
	    dev_id : _SPI_NAND_DEVICE_ID_HYF1GQ4UTACAE,
	    ptr_name : "HEYANG HYF1GQ4UTACAE",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_HEYANG_2,
	    dev_id : _SPI_NAND_DEVICE_ID_HYF2GQ4UTACAE,
	    ptr_name : "HEYANG HYF2GQ4UTACAE",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_PN,
	    dev_id : _SPI_NAND_DEVICE_ID_PN26G01AWSIUG,
	    ptr_name : "PN PN26G01A-X",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_PN,
	    dev_id : _SPI_NAND_DEVICE_ID_PN26G02AWSIUG,
	    ptr_name : "PN PN26G02A-X",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_PN,
	    dev_id : _SPI_NAND_DEVICE_ID_PN26Q01AWSIUG,
	    ptr_name : "PN PN26Q01A-X",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ATO,
	    dev_id : _SPI_NAND_DEVICE_ID_ATO25D1GA,
	    ptr_name : "ATO ATO25D1GA",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_SINGLE,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ATO,
	    dev_id : _SPI_NAND_DEVICE_ID_ATO25D2GA,
	    ptr_name : "ATO ATO25D2GA",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_ATO_2,
	    dev_id : _SPI_NAND_DEVICE_ID_ATO25D2GB,
	    ptr_name : "ATO ATO25D2GB",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    /* FM */
    {
	    ptr_name : "FM FM25S01",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FM,
	    dev_id : _SPI_NAND_DEVICE_ID_FM25S01,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FM FM25S01A",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FM,
	    dev_id : _SPI_NAND_DEVICE_ID_FM25S01A,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FM FM25S02A",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FM,
	    dev_id : _SPI_NAND_DEVICE_ID_FM25S02A,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FM,
	    dev_id : _SPI_NAND_DEVICE_ID_FM25G01B,
	    ptr_name : "FM FM25G01B",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FM,
	    dev_id : _SPI_NAND_DEVICE_ID_FM25G02B,
	    ptr_name : "FM FM25G02B",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FM,
	    dev_id : _SPI_NAND_DEVICE_ID_FM25G02C,
	    ptr_name : "FM FM25G02C",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FM,
	    dev_id : _SPI_NAND_DEVICE_ID_FM25G02,
	    ptr_name : "FM FM25G02",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    /* XTX */
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_XTX,
	    dev_id : _SPI_NAND_DEVICE_ID_XT26G02B,
	    ptr_name : "XTX XT26G02B",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "XTX XT26G01C",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_XTX,
	    dev_id : _SPI_NAND_DEVICE_ID_XT26G01C,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "XTX XT26G02C",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_XTX,
	    dev_id : _SPI_NAND_DEVICE_ID_XT26G02C,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "XTX XT26G01A",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_XTX,
	    dev_id : _SPI_NAND_DEVICE_ID_XT26G01A,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "XTX XT26G02A",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_XTX,
	    dev_id : _SPI_NAND_DEVICE_ID_XT26G02A,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    /* Mira */
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_MIRA,
	    dev_id : _SPI_NAND_DEVICE_ID_PSU1GS20BN,
	    ptr_name : "MIRA PSU1GS20BN",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    /* BIWIN */
    {
	    ptr_name : "BIWIN BWJX08U",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_BIWIN,
	    dev_id : _SPI_NAND_DEVICE_ID_BWJX08U,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "BIWIN BWET08U",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_BIWIN,
	    dev_id : _SPI_NAND_DEVICE_ID_BWET08U,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    /* FORESEE */
    {
	    ptr_name : "FORESEE F35UQA512M",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_F35UQA512M,
	    device_size : _SPI_NAND_CHIP_SIZE_512MBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE F35UQA001G",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_F35UQA001G,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE F35UQA002G",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_F35UQA002G,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE F35SQA512M",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_F35SQA512M,
	    device_size : _SPI_NAND_CHIP_SIZE_512MBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE F35SQA001G",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_F35SQA001G,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE F35SQA002G",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_F35SQA002G,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE FS35ND01GD1F1",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_FS35ND01GD1F1,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE FS35ND01GS1F1",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_FS35ND01GS1F1,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE FS35ND02GS2F1",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_FS35ND02GS2F1,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE FS35ND02GD1F1",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_FS35ND02GD1F1,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE FS35ND01GS1Y2",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_FS35ND01GS1Y2,
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    ptr_name : "FORESEE FS35ND02G-S3Y2",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_FS35ND02GS3Y2,
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_SINGLE,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },
    {
	    ptr_name : "FORESEE FS35ND04G-S2Y2",
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FORESEE,
	    dev_id : _SPI_NAND_DEVICE_ID_FS35ND04GS2Y2,
	    device_size : _SPI_NAND_CHIP_SIZE_4GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_SINGLE,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_DS,
	    dev_id : _SPI_NAND_DEVICE_ID_DS35Q1GA,
	    ptr_name : "DS DS35Q1GA",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_DS,
	    dev_id : _SPI_NAND_DEVICE_ID_DS35M1GA,
	    ptr_name : "DS DS35M1GA",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_DS,
	    dev_id : _SPI_NAND_DEVICE_ID_DS35Q2GA,
	    ptr_name : "DS DS35Q2GA",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_DS,
	    dev_id : _SPI_NAND_DEVICE_ID_DS35M2GA,
	    ptr_name : "DS DS35M2GA",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_DS,
	    dev_id : _SPI_NAND_DEVICE_ID_DS35Q2GB,
	    ptr_name : "DS DS35Q2GB",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_DS,
	    dev_id : _SPI_NAND_DEVICE_ID_DS35M2GB,
	    ptr_name : "DS DS35M2GB",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_PLANE_SELECT_HAVE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FISON,
	    dev_id : _SPI_NAND_DEVICE_ID_CS11G0T0A0AA,
	    ptr_name : "FISON CS11G0T0A0AA",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FISON,
	    dev_id : _SPI_NAND_DEVICE_ID_CS11G1T0A0AA,
	    ptr_name : "FISON CS11G1T0A0AA",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_FISON,
	    dev_id : _SPI_NAND_DEVICE_ID_CS11G0G0A0AA,
	    ptr_name : "FISON CS11G0G0A0AA",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_TYM,
	    dev_id : _SPI_NAND_DEVICE_ID_TYM25D2GA01,
	    ptr_name : "TYM TYM25D2GA01",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_TYM,
	    dev_id : _SPI_NAND_DEVICE_ID_TYM25D2GA02,
	    ptr_name : "TYM TYM25D2GA02",
	    device_size : _SPI_NAND_CHIP_SIZE_2GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },
    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_TYM,
	    dev_id : _SPI_NAND_DEVICE_ID_TYM25D1GA03,
	    ptr_name : "TYM TYM25D1GA03",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_64BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },

    {
	    mfr_id : _SPI_NAND_MANUFACTURER_ID_XINCUN,
	    dev_id : _SPI_NAND_DEVICE_ID_XCSP1AAWHNT,
	    ptr_name : "XINCUN XCSP1AAWH-NT",
	    device_size : _SPI_NAND_CHIP_SIZE_1GBIT,
	    page_size : _SPI_NAND_PAGE_SIZE_2KBYTE,
	    oob_size : _SPI_NAND_OOB_SIZE_128BYTE,
	    erase_size : _SPI_NAND_BLOCK_SIZE_128KBYTE,
	    dummy_mode : SPI_NAND_FLASH_READ_DUMMY_BYTE_APPEND,
	    read_mode : SPI_NAND_FLASH_READ_SPEED_MODE_DUAL,
	    write_mode : SPI_NAND_FLASH_WRITE_SPEED_MODE_SINGLE,
	    feature : SPI_NAND_FLASH_FEATURE_NONE,
    },
};

/* Function to get the size of the table */
size_t get_spi_nand_flash_table_size(void)
{
	return sizeof(spi_nand_flash_tables) / sizeof(struct SPI_NAND_FLASH_INFO_T);
}
