/*
 * spi_nand_flash_feature.h
 * SPI NAND Flash feature definitions.
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#ifndef _SPI_NAND_FLASH_FEATURE_H_
#define _SPI_NAND_FLASH_FEATURE_H_

/* Bitwise feature flags */
#define SPI_NAND_FLASH_FEATURE_NONE 0x00
#define SPI_NAND_FLASH_PLANE_SELECT_HAVE (0x01 << 0)
#define SPI_NAND_FLASH_DIE_SELECT_1_HAVE (0x01 << 1)
#define SPI_NAND_FLASH_DIE_SELECT_2_HAVE (0x01 << 2)

/* SPI NAND Feature Define */
typedef enum
{
	SPI_NAND_FLASH_FEATURE_NONE_ENUM = 0x0,
	SPI_NAND_FLASH_FEATURE_QE_HAVE = 0x1 << 0,
	SPI_NAND_FLASH_FEATURE_CE_ID_HAVE = 0x1 << 1,
	SPI_NAND_FLASH_FEATURE_DUMMY_BYTE_HAVE = 0x1 << 2,
	SPI_NAND_FLASH_FEATURE_ADDRESS_CMD_HAVE = 0x1 << 3,
	SPI_NAND_FLASH_FEATURE_WP_CTRL_HAVE = 0x1 << 4,
	SPI_NAND_FLASH_FEATURE_HOLD_CTRL_HAVE = 0x1 << 5,
	SPI_NAND_FLASH_FEATURE_DDR_MODE_HAVE = 0x1 << 6,
	SPI_NAND_FLASH_FEATURE_PLANE_SELECT_HAVE_ENUM = 0x1 << 7,
	SPI_NAND_FLASH_FEATURE_DIE_SELECT_1_HAVE_ENUM = 0x1 << 8, /* Die select by command */
	SPI_NAND_FLASH_FEATURE_DIE_SELECT_2_HAVE_ENUM = 0x1 << 9  /* Die select by register */
} SPI_NAND_FLASH_FEATURE_T;

#endif /* _SPI_NAND_FLASH_FEATURE_H_ */
